/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConectarMySQL;
import Controlador.ControladorCorreo;
import DAO.DaoAtributoIMP;
import Interface.DaoObjetoAtributo;
import Modelo.DatosEnviarCorreo;
import Modelo.DatosRegistrarBasedato;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author luis caldera
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        correoSesion = new javax.swing.JTextField();
        contraSesion = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        correoElectronico = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Correo electronico");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 30));

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 97, 30));
        getContentPane().add(correoSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 28));
        getContentPane().add(contraSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 190, 28));

        jButton1.setText("Iniciar sesion ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 120, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);
        jPanel1.add(apellido);
        apellido.setBounds(240, 70, 200, 30);

        jLabel5.setText("Crea una cuenta ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 11, 170, 14);
        jPanel1.add(nombre);
        nombre.setBounds(40, 70, 190, 30);

        jLabel6.setText("Nombre ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 50, 50, 14);

        jLabel7.setText("Apellido");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(240, 40, 120, 30);
        jPanel1.add(correoElectronico);
        correoElectronico.setBounds(40, 130, 400, 30);

        jLabel8.setText("Correo electronico");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 110, 150, 14);

        jLabel9.setText("Contraseña   ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 170, 120, 14);
        jPanel1.add(contraseña);
        contraseña.setBounds(40, 190, 190, 30);

        jButton2.setText("Registrarte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 300, 130, 23);

        jLabel3.setText("Telefono");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 230, 90, 14);
        jPanel1.add(telefono);
        telefono.setBounds(40, 250, 190, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 540, 340));

        setBounds(0, 0, 589, 495);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // evalua que los campos no esten basios 
        if (nombre.getText().equals("") || apellido.getText().equals("") || correoElectronico.getText().equals("") || contraseña.getText().equals("") || telefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Porfavor llenar todos los campos... ");
            //  if (Integer.parseInt(telefono.getText()) == 0){JOptionPane.showMessageDialog(null, "Solo numeros porfavor...");}

        } else {
            try {
                DatosRegistrarBasedato dato = new DatosRegistrarBasedato();
                DaoObjetoAtributo de = new DaoAtributoIMP();

                //recibo los datos por la gui de loging para registro de los datos en la base de datos
                dato.setNombre(nombre.getText());
                dato.setApellido(apellido.getText());
                dato.setCorreoElectronico(correoElectronico.getText());
                dato.setContraseña(contraseña.getText());
                dato.setTelefono(Integer.parseInt(telefono.getText()));
                // registrar en la base de datos la informacion optenida de las cajas de texto

                try {

                    de.Registrar(dato);                                         // se dio el guardado en BD

                    //limpiar las cajas de texto
                    nombre.setText("");
                    apellido.setText("");
                    correoElectronico.setText("");
                    contraseña.setText("");
                    telefono.setText("");

                    JOptionPane.showMessageDialog(null, "Registro correcto en la base datos...");
                } catch (Exception e) {
                    System.out.println("no se guardo en la base datos.");       // en caso tal que no se de el guardado en la BD
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "los datos de telefono solo pueden ser numeros (1, 2, 3, 4 )...");
                System.out.println("" + ex.getMessage());
            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ControlMensaje ventana = new ControlMensaje();
        ConectarMySQL cone = new ConectarMySQL();

        try {
            // TODO add your handling code here:
            DaoObjetoAtributo dao = new DaoAtributoIMP();
            DatosRegistrarBasedato dato = new DatosRegistrarBasedato();

            //toma el los datos que se ingresan en las cajas de texto correoSesion y contraSesion que los resibe como parametros el metodo buscarUsusarioRegistrado

            String dat = dao.BuscarUsuarioRegistrado(correoSesion.getText(), contraSesion.getText());

            // JOptionPane.showMessageDialog(this, dat);        // manda un mensaje mostrando el valor de retorno del metodo, que puede ser encontrado o no encontrado

            if ((correoSesion.getText().equals("")) || (contraSesion.getText().equals(""))) {   // evalua que los campos esten llenos

                JOptionPane.showMessageDialog(null, "los campos no pueden estar vacios. ");

            } else if (dat.equals("Usuario encontrado.")) {                                    // evalua que los datos sean correctos

                JOptionPane.showMessageDialog(this, "se encontro el usuairo.");        // manda un mensaje mostrando el valor de retorno del metodo, que puede ser encontrado o no encontrado
               
                ventana.setVisible(true);
                this.dispose();                         // cierra la vemtanita actual

            } if (dat.equals("usuario no fue encontrado.")){
                JOptionPane.showMessageDialog(this, "no se pudo iniciar sesion, intente nuevamente.");
            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());

        }

    }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JPasswordField contraSesion;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JTextField correoElectronico;
    private javax.swing.JTextField correoSesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
